config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  post 'reservations/confirm'
  get 'reservations/confirm'
  post 'reservations/show' => 'reservations#create'
  get 'reservations/show'
  root 'homes#index'
  get 'users/account'
  get 'users/profile'
  patch 'users/profile' => 'users#update'
  get 'rooms/posts'
  get 'rooms/search/result' => 'rooms#search'
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, :room_id, :start_date, :end_date, :total_price, presence: true
  validate :start_date_cannot_be_in_the_past, :end_date_cannot_be_in_start_date

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, ": 過去の日付は使えません")
    end
  end

  def end_date_cannot_be_in_start_date
    if end_date.present? && end_date < start_date
      errors.add(:end_date, ": 開始日より前の日付は使えません")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :reservations

  validates :user_id, :name, :introduction, :price, :address, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :icon
  has_many :rooms
  has_many :reservations

  validates :name, presence: true
  validates :introduction, length:{maximum: 30}
  
  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :icon])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end
  def confirm
    @reservations = Reservation.new(params.permit(:room_id, :start_date, :end_date, :people, :price ))
    @room_price = @reservations.room.price
    @room_start = @reservations.start_date
    @room_end = @reservations.end_date
    @room_day = (@reservations.end_date - @reservations.start_date).to_i
    @room_people = @reservations.people
    @room_sum = @reservations.room.price * @reservations.people * @room_day
  end

  def create
    @reservations = Reservation.new(params.require(:reservation).permit(:user_id, :room_id, :start_date, :end_date, :people, :total_price ))
    if @reservations.save
      flash[:success] = "予約が完了しました"
      redirect_to reservations_show_path
    else
      flash.keep[:danger] = "予約ができませんでした"
      redirect_to room_path(@reservations.room_id)
    end
  end

  def show
    @reservation = Reservation.order("created_at DESC").first
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :move_to_signed_in, except: [:index, :search]
  def index
    @rooms = Room.all
  end
  
  def search
    if params[:flag]
      @rooms = Room.where("name LIKE ? OR address LIKE ? OR introduction LIKE ? OR price LIKE ?", "%#{params[:word]}%", "%#{params[:word]}%", "%#{params[:word]}%", "%#{params[:word]}%")
    else
      @rooms = Room.where("address LIKE ?", "%#{params[:word]}%")
    end
  end

  def new
    @room = Room.new
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def create
    @room = Room.new(params.require(:room).permit(:user_id, :name, :introduction, :price, :address, :image))
    if @room.save
      flash[:success] = "ルームを新しく登録しました"
      redirect_to :rooms
    else
      flash.keep[:danger] = "ルームを登録できませんでした"
      render "new"
    end
  end
  
  def posts
    @rooms = Room.where(user_id: current_user.id)
  end
  
  def move_to_signed_in
    unless user_signed_in?
      redirect_to '/users/sign_in'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
  end
  
  def profile
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(params.require(:user).permit(:name, :introduction, :icon))
      flash[:success] = "プロフィールを更新しました"
      redirect_to users_account_path
    else
      flash.keep[:danger] = "プロフィールを更新できませんでした"
      render users_profile_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="top">
  <div class="top-main">
    <div class="container">
      <div class="row col-lg-6">
        <div class="form-fream">
          <div class="form-area">
            <p class="form-area-title mb-4">Potepan Shareでまだ体験したことない旅をしよう</p>
            <%= form_with url: "/rooms/search/result", method: :get do |f| %>
              <%= f.label :word, "エリア" %>
              <%= f.text_field :word, placeholder: "東京", class: "form-control mb-4" %>
              <%= f.submit "探す", class: "form-control btn-primary mb-4", role: "button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="panel-area m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class="row">
        <div class="panel-item col-lg-3 col-6">
          <%= link_to rooms_search_result_path(word: "東京") do %><span>東京</span>
          <%= image_tag "/assets/img_tokyo.jpg", class: "panel-image" %>
          <% end %>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <%= link_to rooms_search_result_path(word: "大阪") do %><span>大阪</span>
          <%= image_tag "/assets/img_osaka.jpg", class: "panel-image" %>
          <% end %>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <%= link_to rooms_search_result_path(word: "京都") do %><span>京都</span>
          <%= image_tag "/assets/img_kyoto.jpg", class: "panel-image" %>
          <% end %>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <%= link_to rooms_search_result_path(word: "札幌") do %><span>札幌</span>
          <%= image_tag "/assets/img_sapporo.jpg", class: "panel-image"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>BookingApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <header class="header">
      <%= render "shared/header" %>
    </header>
    <%= render "shared/flash" %>
    <%= yield %>
    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5 class="price-icon"><%= @room_price %>/ 日</h5>
        <div class="reservations-new-date-select">
          <%= form_with model:@reservations, url: reservations_show_path, class: "new_reservation" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :room_id, value: @reservations.room_id %>
            <%= f.hidden_field :people, value: @room_people %>
            <%= f.hidden_field :total_price, value: @room_sum %>
            <%= f.label :start_date, "開始日" %>
            <%= f.date_field :start_date, value: @room_start, readonly: true, class: "form-control mb-4" %>
            <%= f.label :end_date, "終了日" %>
            <%= f.date_field :end_date, value: @room_end, readonly: true, class: "form-control mb-4" %>
            <h6 class="reservations-new-check-content">使用日数：<%= @room_day %>日</h6>
            <h6 class="reservations-new-check-content">人数：<%= @room_people %>人</h6>
            <%= f.label :total_price, "合計金額" %>
            <%= f.text_field :total_price, value: @room_sum, readonly: true, class: "form-control mb-4" %>
            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
            <%= f.submit "予約を確定", class: "btn btn-primary form-control my-3" %>
            <%= link_to "ルーム詳細に戻る", "/rooms/#{@reservations.room_id}", class: "btn btn-secondary form-control" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>合計料金</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |room| %>
        <tr>
          <td>
            <%= link_to room.room, class: "link_deco_none" do %>
              <%= image_tag room.room.image, class: "reservations-image" %>
            <% end %>
          </td>
          <td class="posts-name">
            <%= link_to room.room do %>
              <%= room.room.name %>
            <% end %>
          </td>
          <td class="posts-content"><%= room.room.introduction %></td>
          <td>¥<%= room.total_price %></td>
          <td><%= room.start_date%></td>
          <td><%= room.end_date %></td>
          <td><%= room.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user"> 
  <div class="row">
    <div class="col-md-12 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
              <label class="col-md-3" for="room">予約した部屋</label>
              <div class="col-md-9"><%= @reservation.room.name %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
              <label class="col-md-3" for="start_date">開始日</label>
              <div class="col-md-9"><%= @reservation.start_date %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
              <label class="col-md-3" for="end_date">終了日</label>
              <div class="col-md-9"><%= @reservation.end_date %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
              <label class="col-md-3" for="end_date">価格</label>
              <div class="col-md-9"><%= @reservation.total_price %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
  <div class="container-fiuld room">
    <h4>検索結果：</h4>
    <div class="row">
      <% @rooms.each do |room| %>
        <div class="col-sm-6 col-lg-4 col-xl-3">
          <div class="room-frame-inner">
            <%= link_to room do %>
              <div class="room-image-out">
                <%= image_tag room.image, class: "room-image"%>
              </div>
              <div class="room-profile">
                <p class="room-profile-name"><%= room.name %></p>
                <p class="room-profile-city"><%= room.address %></p>
                <p class="room-profile-price price-icon"><%= room.price %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/rooms/new.html.erb
<%= render "shared/error", obj: @room %>
<div class="container-fiuld room-new">
  <div class="row">
    <div class="col-lg-2 room-nav room-nav-pc d-lg-block d-none">
      <ul>
          <li><a href="/rooms/new">基本情報</a></li>
      </ul>
    </div>
    <div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
      <ul>
          <li><a href="/rooms/new">基本情報</a></li>
      </ul>
    </div>
    <div class="col-lg-10 room-view">
      <div class="room-view-box">
        <%= form_with model:@room, class: "new_room", id: "new_room" do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="update-content">
              <div class="row"><h5>ルーム情報登録</h5></div>
            </div>
            <div class="update-content">
              <div class="row">
                <%= f.label :name, "ルーム名", class: "col-md-3" %>
                <%= f.text_field :name, class: "form-control mb-4 col-md-9" %>
              </div>
            </div>
            <div class="update-content">
              <div class="row">
                <%= f.label :introduction, "ルーム紹介", class: "col-md-3" %>
                <%= f.text_area :introduction, class: "form-control mb-4 col-md-9" %>
              </div>
            </div>
            <div class="update-content">
              <div class="row">
                <%= f.label :price, "料金", class: "col-md-3" %>
                <%= f.text_field :price, class: "form-control mb-4 col-md-9", placeholder: "一日あたりの料金を入力" %>
              </div>
            </div>
            <div class="update-content">
              <div class="row">
                <%= f.label :address, "住所", class: "col-md-3" %>
                <%= f.text_field :address, class: "form-control mb-4 col-md-9" %>
              </div>
            </div>
            <div class="update-content">
              <div class="row">
                <%= f.label :image, "ルーム画像", class: "col-md-3" %>
                <%= f.file_field :image, class: "mb-4 col-md-9" %>
              </div>
            </div>
            <div class="update-content">
              <div class="row">
                <%= f.submit "登録", class: "btn_submit", class: "col-md-2 btn btn-primary mx-3" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/posts.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td>
            <%= link_to room, class: "link_deco_none" do %>
              <%= image_tag room.image, class: "room-posts-image" %>
            <% end %>
          </td>
          <td class="posts-name">
            <%= link_to room do %><%= room.name %><% end %>
          </td>
          <td class="posts-content"><%= room.introduction %></td>
          <td>¥<%= room.price %></td>
          <td><%= room.created_at%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="container-fiuld room">
  <h4>検索結果：<%= @rooms.count %>件</h4>
  <div class="row">
    <% @rooms.each do |room| %>
      <div class="col-sm-6 col-lg-4 col-xl-3">
        <div class="room-frame-inner">
          <%= link_to room do %>
            <div class="room-image-out"><%= image_tag room.image, class: "room-image"%></div>
            <div class="room-profile">
              <p class="room-profile-name"><%= room.name %></p>
              <p class="room-profile-city"><%= room.address %></p>
              <p class="room-profile-price price-icon">¥<%= room.price %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag @room.image, class: "room-show-image" %>
      <div class="room-show-detile">
        <div class="room-show-profile">
          <p class="room-show-profile-name"><%= @room.name %></p>
          <p class="room-show-profile-address"><%= @room.address %></p>
        </div>
      </div>
      <p class="room-show-detile-content"><%= @room.introduction %></p>
    </div>
    <div class="col-md-4">
      <div class="room-show-nav">
        <h3 class="price-icon">¥<%= @room.price %>/日</h3>
        <div class="room-show-date-select">
          <%= form_with model:@reservations, url: reservations_confirm_path do |f| %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.label :start_date, "開始日" %>
            <%= f.date_field :start_date, class: "form-control mb-4" %>
            <%= f.label :end_date, "終了日" %>
            <%= f.date_field :end_date, class: "form-control mb-4" %>
            <%= f.label :people, "人数" %>
            <%= f.number_field :people, min: 1, class: "form-control mb-4" %>
            <%= f.submit "予約する", class: "btn_submit", class: "btn btn-primary form-control" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag(:p, message, class: "alert alert-#{key}") %>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand navbar-dark p-1" style="background-color:#111;">   
  <%= link_to root_path, class: "flex-grow-1" do %>
    <img src="/assets/logo.png" alt="ポテパンシェア" >
  <% end %>
  <%= form_with url: "/rooms/search/result", method: :get, class: "header-sharch d-none d-lg-block" do |f| %>
      <%= f.text_field :word, placeholder: "エリア", class: "form-control " %>
    <i class="fas fa-map-marker-alt"></i>
  <% end %>
  <%= form_with url: "/rooms/search/result", method: :get, class: "header-sharch d-none d-lg-block ml-1" do |f| %>
      <%= f.hidden_field :flag, :value => true %>
      <%= f.text_field :word, placeholder: "キーワード", class: "form-control" %>  
    <i class="fas fa-search"></i>
  <% end %>
  <% if user_signed_in? %>
      <div class="nav-item user-name ml-3">
        <%= current_user.name %>
      </div>
      <div class=" nav-item dropdown mx-3">
        <% if current_user.icon.present? %>
            <p class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.icon.url, class: "host-icon" %></p>
        <% else %>
            <p class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= image_tag 'default.png', class: "host-icon" %></p>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" >
          <%= link_to "ルーム登録", new_room_path, class: "dropdown-item" %>
          <%= link_to "予約済みルーム一覧", reservations_index_path, class: "dropdown-item" %>
          <%= link_to "登録済みルーム一覧", rooms_posts_path, class: "dropdown-item" %>
          <%= link_to "設定", users_account_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
  <% else %>
    <div class="nav-item">
      <%= link_to "ログイン", user_session_path, class: "btn btn-primary my-2 mx-3" %>
      <%= link_to "登録する", new_user_registration_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</nav>

app/views/users/account.html.erb
<div class="container-fiuld user"> 
  <div class="row">
    <%= render "devise/shared/users_setting" %>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
            <div class="row">
                <h5>アカウント</h5>
            </div>
        </div>
        <div class="update-content">
            <div class="row">
                <label class="col-md-3" for="email">メールアドレス</label>
                <div class="col-md-9"><%= current_user.email %></div>
            </div>
        </div>
        <div class="update-content">
            <div class="row">
                <label class="col-md-3" for="password">パスワード</label>
                <div class="col-md-9">*********</div>
            </div>
        </div>
        <div class="update-content">
            <div class="row">
              <%= link_to '編集', edit_user_registration_path, class: "col-md-2 btn btn-primary mx-3" %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<%= render "shared/error", obj: @user %>
<div class="container-fiuld user">
  <div class="row">
    <%= render "devise/shared/users_setting"%>
    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>プロフィール</h5>
          </div>
        </div>
        <%= form_with model:@user, url: users_profile_path, class: "edit_user" do |f| %>
          <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if current_user.icon.present? %>
                    <%= image_tag current_user.icon.url, class: "icon-image host-icon" %>
                  <% else %>
                    <%= image_tag 'default.png', class: "icon-image host-icon" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label "アイコン画像", class: "col-md-3" %>
              <%= f.file_field :icon, class: "mb-4 col-md-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :name, class: "col-md-3" %>
              <%= f.text_field :name, class: "form-control mb-4 col-md-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label "自己紹介",  class: "col-md-3" %>
              <%= f.text_area :introduction, class:"form-control mb-4 col-md-9" %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.submit "更新", class: "col-md-2 btn btn-primary mx-3" %>
            </div>
          </div>
        <% end %>
      </div> 
    </div>  
  </div>
</div>


  
    
   